In [37]:
import numpy as np
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# **Create DataFrame**

In [38]:
# Simulating the data in a dictionary format
data = {
    "Name": ["Alex", "John", "Mathew", "Matt", "Jacob"],
    "Cust_I": [123457, 123458, 123459, 12345, 1256],
    "Open_Dt": ["20101012", "20101012", "20101012", "20101012", "20101012"],
    "Consul_Dt": ["20121013", "20121013", "20121013", "20121013", "20121013"],
    "VAC_ID": ["MVD", "MVD", "MVD", "MVD", "MVD"],
    "DR_Name": ["Paul", None, None, None, None],
    "State": ["SA", "TN", "WAS", "BOS", "VIC"],
    "County": ["USA", "IND", "PHIL", "NYC", "AU"],
    "DOB": ["06031987", "06031987", "06031987", "06031987", "06031987"],
    "FLAG": ["A", "A", "A", "A", "A"]
}

In [39]:
# Creating the DataFrame
df = pd.DataFrame(data)

In [40]:
df.head()

,Name,Cust_I,Open_Dt,Consul_Dt,VAC_ID,DR_Name,State,County,DOB,FLAG
0,Alex,123457,20101012,20121013,MVD,Paul,SA,USA,06031987,A
1,John,123458,20101012,20121013,MVD,None,TN,IND,06031987,A
2,Mathew,123459,20101012,20121013,MVD,None,WAS,PHIL,06031987,A
3,Matt,12345,20101012,20121013,MVD,None,BOS,NYC,06031987,A
4,Jacob,1256,20101012,20121013,MVD,None,VIC,AU,06031987,A

In [41]:
df.shape

(5, 10)

In [42]:
# Convert date strings to datetime format
df['Open_Dt'] = pd.to_datetime(df['Open_Dt'], format='%Y%m%d')
df['Consul_Dt'] = pd.to_datetime(df['Consul_Dt'], format='%Y%m%d')
df['DOB'] = pd.to_datetime(df['DOB'], format='%d%m%Y')

# **Calculate Age and Days Since Last Consulted**

In [43]:
#  Calculate Age and Days Since Last Consulted
df['Age'] = df['DOB'].apply(lambda x: datetime.now().year - x.year)
df['Days_Since_Last_Consulted'] = (datetime.now() - df['Consul_Dt']).dt.days

In [44]:
df.head()

,Name,Cust_I,Open_Dt,Consul_Dt,VAC_ID,DR_Name,State,County,DOB,FLAG,Age,Days_Since_Last_Consulted
0,Alex,123457,2010-10-12,2012-10-13,MVD,Paul,SA,USA,1987-03-06,A,37,4394
1,John,123458,2010-10-12,2012-10-13,MVD,None,TN,IND,1987-03-06,A,37,4394
2,Mathew,123459,2010-10-12,2012-10-13,MVD,None,WAS,PHIL,1987-03-06,A,37,4394
3,Matt,12345,2010-10-12,2012-10-13,MVD,None,BOS,NYC,1987-03-06,A,37,4394
4,Jacob,1256,2010-10-12,2012-10-13,MVD,None,VIC,AU,1987-03-06,A,37,4394

In [45]:
df.dtypes

Name                                 object
Cust_I                                int64
Open_Dt                      datetime64[ns]
Consul_Dt                    datetime64[ns]
VAC_ID                               object
DR_Name                              object
State                                object
County                               object
DOB                          datetime64[ns]
FLAG                                 object
Age                                   int64
Days_Since_Last_Consulted             int64
dtype: object

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       5 non-null      object
 1   Cust_I                     5 non-null      int64
 2   Open_Dt                    5 non-null      datetime64[ns]
 3   Consul_Dt                  5 non-null      datetime64[ns]
 4   VAC_ID                     5 non-null      object
 5   DR_Name                    1 non-null      object
 6   State                      5 non-null      object
 7   County                     5 non-null      object
 8   DOB                        5 non-null      datetime64[ns]
 9   FLAG                       5 non-null      object
 10  Age                        5 non-null      int64
 11  Days_Since_Last_Consulted  5 non-null      int64
dtypes: datetime64[ns](3), int64(3), object(6)
memory usage: 608.0+ bytes

# **Filter Customers Based on Days Since Last Consultation > 30**

In [47]:
#  Filter Customers with Days Since Last Consulted > 30
df_filtered = df[df['Days_Since_Last_Consulted'] > 30]

# **Split Data by Country**

In [35]:
#  Split data by County and save into separate DataFrames
for country in df_filtered['County'].unique():
    country_df = df_filtered[df_filtered['County'] == country]
    print(f"Data for {country}:")
    print(country_df)
    country_df.to_csv(f"Table_{country}.csv", index=False)

Data for USA:
   Name  Cust_I    Open_Dt  Consul_Dt VAC_ID DR_Name State County        DOB  \
0  Alex  123457 2010-10-12 2012-10-13    MVD    Paul    SA    USA 1987-03-06

  FLAG  Age  Days_Since_Last_Consulted
0    A   37                       4394
Data for IND:
   Name  Cust_I    Open_Dt  Consul_Dt VAC_ID DR_Name State County        DOB  \
1  John  123458 2010-10-12 2012-10-13    MVD    None    TN    IND 1987-03-06

  FLAG  Age  Days_Since_Last_Consulted
1    A   37                       4394
Data for PHIL:
     Name  Cust_I    Open_Dt  Consul_Dt VAC_ID DR_Name State County  \
2  Mathew  123459 2010-10-12 2012-10-13    MVD    None   WAS   PHIL

         DOB FLAG  Age  Days_Since_Last_Consulted
2 1987-03-06    A   37                       4394
Data for NYC:
   Name  Cust_I    Open_Dt  Consul_Dt VAC_ID DR_Name State County        DOB  \
3  Matt   12345 2010-10-12 2012-10-13    MVD    None   BOS    NYC 1987-03-06

  FLAG  Age  Days_Since_Last_Consulted
3    A   37                       4394
Data for AU:
    Name  Cust_I    Open_Dt  Consul_Dt VAC_ID DR_Name State County        DOB  \
4  Jacob    1256 2010-10-12 2012-10-13    MVD    None   VIC     AU 1987-03-06

  FLAG  Age  Days_Since_Last_Consulted
4    A   37                       4394

# **Handling Customer Relocation**

In [36]:
# Handling Customer Relocation (based on latest consultation date)
df_sorted = df.sort_values(['Cust_I', 'Consul_Dt'], ascending=[True, False])
df_latest = df_sorted.drop_duplicates(subset='Cust_I', keep='first')

# Show the latest records
df_latest

,Name,Cust_I,Open_Dt,Consul_Dt,VAC_ID,DR_Name,State,County,DOB,FLAG,Age,Days_Since_Last_Consulted
4,Jacob,1256,2010-10-12,2012-10-13,MVD,None,VIC,AU,1987-03-06,A,37,4394
3,Matt,12345,2010-10-12,2012-10-13,MVD,None,BOS,NYC,1987-03-06,A,37,4394
0,Alex,123457,2010-10-12,2012-10-13,MVD,Paul,SA,USA,1987-03-06,A,37,4394
1,John,123458,2010-10-12,2012-10-13,MVD,None,TN,IND,1987-03-06,A,37,4394
2,Mathew,123459,2010-10-12,2012-10-13,MVD,None,WAS,PHIL,1987-03-06,A,37,4394